services:
  external:
    networks:
      default:
        ipv4_address: "${IPV4_CADDY_EXTERNAL}/${IPV4_NETMASK}"
        x-incus:
          ipv4.gateway: "${IPV4_GATEWAY}"

  internal:
    networks:
      default:
        ipv4_address: "${IPV4_CADDY_INTERNAL}/${IPV4_NETMASK}"
        x-incus:
          ipv4.gateway: "${IPV4_GATEWAY}"

networks:
  default:
    external: ${NET_EXTERNAL}
    name: "${NET_NAME}"
