FROM busybox:glibc

ARG TARGETPLATFORM
ARG VERSION

COPY ${TARGETPLATFORM}/ic-healthd /usr/local/bin/ic-healthd

USER 65534:65534

# 9153 is /metrics, /health and /ready.
EXPOSE 9153

CMD ["ic-healthd", "run"]
