services:
  docker-registry:
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:5000"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 30s
      start_interval: 5s
    networks:
      default:
        ipv4_address: ${DOCKERIO_IPV4}/${IPV4_NETMASK}

  ghcr-registry:
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:5000"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 30s
      start_interval: 5s
    networks:
      default:
        ipv4_address: ${GHCRIO_IPV4}/${IPV4_NETMASK}

  gitlab-registry:
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:5000"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 30s
      start_interval: 5s
    networks:
      default:
        ipv4_address: ${GITLAB_IPV4}/${IPV4_NETMASK}

networks:
  default:
    x-incus:
      ipv4.address: ${GATEWAY_IPV4}/${IPV4_NETMASK}
    x-incus-compose:
      network: ${NETWORK}
volumes:
  docker:
    x-incus-compose:
      pool: ${STORAGE_POOL}
  ghcr:
    x-incus-compose:
      pool: ${STORAGE_POOL}
  gitlab:
    x-incus-compose:
      pool: ${STORAGE_POOL}
