name: Commits

on:
  pull_request:

permissions:
  contents: read

jobs:
  dco-check:
    permissions:
      pull-requests: read # for tim-actions/get-pr-commits to get list of commits from the PR
    name: Signed-off-by (DCO)
    runs-on: ubuntu-24.04
    steps:
      - name: Check that all commits are signed-off
        uses: KineticCafe/actions-dco@v3.1.0
